apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dc3.service: dc3-monitor
  namespace: dc3
  name: dc3-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"
      dc3.service: dc3-monitor
  template:
    metadata:
      labels:
        dc3.version: develop
        dc3.network/dc3net: "true"
        dc3.service: dc3-monitor
    spec:
      containers:
        - image: pnoker/dc3-monitor:3.0
          name: dc3-monitor
          ports:
            - containerPort: 8200
      hostname: dc3-monitor
      restartPolicy: Always