apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-mongo
  namespace: dc3
  name: dc3-mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-mongo
    spec:
      containers:
      - image: pnoker/dc3-mongo:3.0
        name: dc3-mongo
        ports:
        - containerPort: 27017
        resources: {}
      hostname: dc3-mongo
      restartPolicy: Always
status: {}
