apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-redis
  namespace: dc3
  name: dc3-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-redis
    spec:
      containers:
      - image: pnoker/dc3-redis:3.0
        name: dc3-redis
        ports:
        - containerPort: 6379
        resources: {}
      hostname: dc3-redis
      restartPolicy: Always
status: {}
