apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-auth
  namespace: dc3
  name: dc3-auth
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-auth
    spec:
      containers:
      - image: pnoker/dc3-auth:3.0
        name: dc3-auth
        ports:
        - containerPort: 8400
        resources: {}
      hostname: dc3-auth
      restartPolicy: Always
status: {}
