apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-gateway
  namespace: dc3
  name: dc3-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-gateway
    spec:
      containers:
      - image: pnoker/dc3-gateway:3.0
        name: dc3-gateway
        ports:
        - containerPort: 8000
        resources: {}
      hostname: dc3-gateway
      restartPolicy: Always
status: {}
