apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-opcua
  namespace: dc3
  name: dc3-opcua
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-opcua
    spec:
      containers:
      - image: pnoker/dc3-opcua:3.0
        name: dc3-opcua
        ports:
        - containerPort: 8802
        resources: {}
      hostname: dc3-opcua
      restartPolicy: Always
status: {}
