apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-mysql
  namespace: dc3
  name: dc3-mysql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-mysql
    spec:
      containers:
      - image: pnoker/dc3-mysql:3.0
        name: dc3-mysql
        ports:
        - containerPort: 3306
        resources: {}
      hostname: dc3-mysql
      restartPolicy: Always
status: {}
