apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-rabbitmq
  namespace: dc3
  name: dc3-rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-rabbitmq
    spec:
      containers:
      - image: pnoker/dc3-rabbitmq:3.0
        name: dc3-rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 1883
        - containerPort: 61613
        - containerPort: 15672
        resources: {}
      hostname: dc3-rabbitmq
      restartPolicy: Always
status: {}
