apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-nginx
  namespace: dc3
  name: dc3-nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-nginx
    spec:
      containers:
      - image: pnoker/alpine-nginx:rtmp
        name: dc3-nginx
        ports:
        - containerPort: 1935
        resources: {}
      hostname: dc3-nginx
      restartPolicy: Always
status: {}
