apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dc3-rtmp
  namespace: dc3
  name: dc3-rtmp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/dc3net: "true"
        io.kompose.service: dc3-rtmp
    spec:
      containers:
      - image: pnoker/dc3-rtmp:3.0
        name: dc3-rtmp
        ports:
        - containerPort: 8803
        resources: {}
      hostname: dc3-rtmp
      restartPolicy: Always
status: {}
