server:
  port: 8200
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: dc3/logs/dc3-register-product-1.log

eureka:
  instance:
    metadata-map:
      user.name: admin
      user.password: admin
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/