server:
  port: 8840
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  security:
    user:
      name: ENC(bmSPDpfLV5VKUJhtcec+Hw==)
      password: ENC(egd+8ZV2DzqcWqv6IC7YxA==)
  thymeleaf:
    cache: false
    enabled: true
    check-template: true
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 1024MB

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

jasypt:
  encryptor:
    password: M82tHF1EjfWpnXzG

logging:
  file: dc3/logs/transfer/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8100/eureka/