server:
  port: 8800
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 日志配置
logging:
  file: dc3/logs/service/center/dc3-service-center1.log

# Eureka 服务中心
eureka:
  instance:
    hostname: service1
  client:
    serviceUrl:
      defaultZone: http://service2:8801/eureka/,http://service3:8802/eureka/