server:
  port: 8801
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

# 日志配置
logging:
  file: dc3/logs/service/center/dc3-service-center-product-2.log

# Eureka 服务中心
eureka:
  instance:
    hostname: service2
  client:
    serviceUrl:
      defaultZone: http://service1:8800/eureka/