server:
  port: 8802
  undertow:
    io-threads: 2
    worker-threads: 20
    buffer-size: 512

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  security:
    user:
      name: dc3
      password: dc3
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        caffeine:
          spec: initialCapacity=10,maximumSize=500,expireAfterAccess=600s

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
      useGzipDecoder: true

hystrix:
  threadpool:
    default:
      coreSize: 20

logging:
  level:
    com.pnoker: DEBUG
  file:
    name: dc3/logs/transfer/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@dc3-register:8100/eureka/
