server:
  port: 8400

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    username: root
    password: dc3
  redis:
    password: dc3
    database: 2
  cache:
    redis:
      time-to-live: 10M

logging:
  level:
    com.pnoker: DEBUG
  file:
    name: dc3/logs/center/${spring.application.name}.log