language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - sudo service mysql stop
  - ps -aux|grep mysql
  - docker pull pnoker/dc3-mariadb:3.0 pnoker/dc3-redis:3.0 pnoker/dc3-rabbitmq:3.0
  - docker run -d --name dc3-mariadb -p 3306:3306 -h iotdc3.mariadb pnoker/dc3-mariadb:3.0
  - docker run -d --name dc3-redis -p 6379:6379 -h iotdc3.redis pnoker/dc3-redis:3.0
  - docker run -d --name dc3-rabbitmq -p 5672:5672 -p 1883:1883 -p 61613:61613 -p 15672:15672 -h iotdc3.rabbitmq pnoker/dc3-rabbitmq:3.0
branches:
  only:
    - master
install: mvn -B clean install -Dgpg.skip=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
