language: java
jdk:
- oraclejdk8
services:
- docker
before_install:
- docker pull pnoker/dc3-mariadb:3.0
- docker pull pnoker/dc3-redis:3.0
- docker pull pnoker/dc3-rabbitmq:3.0
- docker run --name dc3-mariadb -p 3306:3306 -d pnoker/dc3-mariadb:3.0 iotdc3.mariadb
branches:
  only:
  - master
install: mvn -B clean install -Dgpg.skip=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true