version: '3'
services:
  # 配置 docker compose
  dc3-gateway:
    build:
      context: ./
      dockerfile: ./dc3-gateway/Dockerfile
    restart: always
    ports:
      - 8000:8000
    links:
      - dc3-register:iotdc3.register
    container_name: dc3-gateway
    hostname: iotdc3.gateway
    image: dc3-gateway:3.0

  dc3-register:
    build:
      context: ./
      dockerfile: ./dc3-center/dc3-register/Dockerfile
    restart: always
    ports:
      - 8100:8100
    container_name: dc3-register
    hostname: iotdc3.register
    image: dc3-register:3.0

  dc3-monitor:
    build:
      context: ./
      dockerfile: ./dc3-center/dc3-monitor/Dockerfile
    restart: always
    ports:
      - 8200:8200
    container_name: dc3-monitor
    hostname: iotdc3.monitor
    image: dc3-monitor:3.0

  dc3-dbs:
    build:
      context: ./
      dockerfile: ./dc3-center/dc3-dbs/Dockerfile
    restart: always
    ports:
      - 8300:8300
    container_name: dc3-dbs
    hostname: iotdc3.dbs
    image: dc3-dbs:3.0

  dc3-collect:
    build:
      context: ./
      dockerfile: ./dc3-center/dc3-collect/Dockerfile
    restart: always
    ports:
      - 8500:8500
    container_name: dc3-collect
    hostname: iotdc3.collect
    image: dc3-collect:3.0

  dc3-manager:
    build:
      context: ./
      dockerfile: ./dc3-device/dc3-manager/Dockerfile
    restart: always
    ports:
      - 8600:8600
    container_name: dc3-manager
    hostname: iotdc3.manager
    image: dc3-manager:3.0

  dc3-group:
    build:
      context: ./
      dockerfile: ./dc3-device/dc3-group/Dockerfile
    restart: always
    ports:
      - 8700:8700
    container_name: dc3-group
    hostname: iotdc3.group
    image: dc3-group:3.0

  dc3-opc:
    build:
      context: ./
      dockerfile: ./dc3-transfer/dc3-opc/Dockerfile
    restart: always
    ports:
      - 8810:8810
    container_name: dc3-opc
    hostname: iotdc3.opc
    image: dc3-opc:3.0

  dc3-opc-ua:
    build:
      context: ./
      dockerfile: ./dc3-transfer/dc3-opc-ua/Dockerfile
    restart: always
    ports:
      - 8820:8820
    container_name: dc3-opc-ua
    hostname: iotdc3.opcua
    image: dc3-opc-ua:3.0

  dc3-rtmp:
    build:
      context: ./
      dockerfile: ./dc3-transfer/dc3-rtmp/Dockerfile
    restart: always
    ports:
      - 8830:8830
    container_name: dc3-rtmp
    hostname: iotdc3.rtmp
    image: dc3-rtmp:3.0

  dc3-resource:
    build:
      context: ./
      dockerfile: ./dc3-transfer/dc3-resource/Dockerfile
    restart: always
    ports:
      - 8840:8840
    container_name: dc3-resource
    hostname: iotdc3.resource
    image: dc3-resource:3.0