server:
  port: 8300
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
spring:
  application:
    name: dc3-websocket

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/web/dc3-websocket.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/