server:
  port: 8500
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
spring:
  application:
    name: dc3-devices

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/dc3-devices-client.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

device:
  client:
    encryp:
      aes:
        private-key: x
      rsa:
        public-key: x
        private-key: x