server:
  port: 8400
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  security:
    user:
      name: dc3
      password: dc3
  redis:
    host: dc3.redis
    port: 6379
    password: ${spring.security.user.password}
    database: 1
    timeout: 15S
    jedis:
      pool:
        max-idle: 16
        min-idle: 4
  transaction:
    rollback-on-commit-failure: true
  cache:
    type: redis
    cache-names: dc3-auth-cache
    redis:
      time-to-live: 60S

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR
  file:
    name: dc3/logs/center/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@dc3.register:8100/eureka/
