server:
  port: 8817
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/dc3-plc-s7-product.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/