server:
  port: 8620
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
spring:
  application:
    name: dc3-plc-s7
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/dc3-plc-s7.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/