device:
  client:
    encryp:
      aes:
        private-key: x
      rsa:
        public-key: x
        private-key: x

server:
  port: 8700
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: iotdc3
      password: iotdc3
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:dc3/sqlite/dc3-group.db
    username:
    password:
    sql-script-encoding: utf-8
    hikari:
      pool-name: iot-dc3-group-hikaricp
      max-lifetime: 1765000
      maximum-pool-size: 16
      minimum-idle: 4

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: dc3_

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/device/${spring.application.name}.log
  level:
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@iotdc3.register:8100/eureka/