server:
  port: 8500
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  security:
    user:
      name: ENC(bmSPDpfLV5VKUJhtcec+Hw==)
      password: ENC(egd+8ZV2DzqcWqv6IC7YxA==)
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:sqlite/dc3-group.db
    username:
    password:
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: dc3_group_

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

jasypt:
  encryptor:
    password: M82tHF1EjfWpnXzG

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/device/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8100/eureka/

device:
  client:
    encryp:
      aes:
        private-key: x
      rsa:
        public-key: x
        private-key: x