server:
  port: 8500
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
spring:
  application:
    name: dc3-group
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:sqlite/dc3-group.sqlite
    username:
    password:
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: dc3_group_

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/device/dc3-client.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

device:
  client:
    encryp:
      aes:
        private-key: x
      rsa:
        public-key: x
        private-key: x