server:
  port: 8300
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  security:
    user:
      name: ENC(bmSPDpfLV5VKUJhtcec+Hw==)
      password: ENC(egd+8ZV2DzqcWqv6IC7YxA==)
  redis:
    host: localhost
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/iot-dc3?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
    sql-script-encoding: utf-8
    hikari:
      pool-name: iot-dc3-dbs-hikaricp
      max-lifetime: 1765000
      maximum-pool-size: 16
      minimum-idle: 4

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: iot_

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

jasypt:
  encryptor:
    password: M82tHF1EjfWpnXzG

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/center/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8100/eureka/