server:
  port: 8300
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: iotdc3
      password: iotdc3
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://iotdc3.mariadb:3306/iot-dc3?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: iotdc3
    sql-script-encoding: utf-8
    hikari:
      pool-name: iot-dc3-dbs-hikaricp
      max-lifetime: 1765000
      maximum-pool-size: 16
      minimum-idle: 4
  data:
    mongodb:
      host: iotdc3.mongodb
      port: 27017
      database: iot-dc3
      username: root
      password: ${spring.security.user.password}
  redis:
    host: iotdc3.redis
    port: 6379
    password: ${spring.security.user.password}
    database: 1
    timeout: 1H
    jedis:
      pool:
        max-idle: 16
        min-idle: 4
  transaction:
    rollback-on-commit-failure: true
  cache:
    type: redis
    cache-names: dc3-dbs-rediscache
    redis:
      time-to-live: 10M

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapping
  global-config:
    banner: false
    db-config:
      table-prefix: dc3_
      logic-delete-value: 1
      logic-not-delete-value: 0


pagehelper:
  helper-dialect: mysql
  page-size-zero: true
  reasonable: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/center/${spring.application.name}.log
  level:
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@iotdc3.register:8100/eureka/
