server:
  port: 8300
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  security:
    user:
      name: iotdc3
      password: ENC(egd+8ZV2DzqcWqv6IC7YxA==) #iotdc3
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://iotdc3.mariadb:3306/iot-dc3?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ENC(egd+8ZV2DzqcWqv6IC7YxA==) #iotdc3
    sql-script-encoding: utf-8
    hikari:
      pool-name: iot-dc3-dbs-hikaricp
      max-lifetime: 1765000
      maximum-pool-size: 16
      minimum-idle: 4
  data:
    mongodb:
      host: iotdc3.mongo
      port: 27017
      database: iot-dc3
      username: root
      password: ENC(egd+8ZV2DzqcWqv6IC7YxA==) #iotdc3
  redis:
    host: iotdc3.redis
    port: 6379
    password: ENC(egd+8ZV2DzqcWqv6IC7YxA==) #iotdc3
    database: 1
    timeout: 60s
    jedis:
      pool:
        max-idle: 16
        min-idle: 4
  transaction:
    rollback-on-commit-failure: true
  cache:
    type: redis
    cache-names: iot-dc3-dbs-rediscache
    redis:
      time-to-live: 10m

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: iot_
  mapper-locations: classpath*:/mapping

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

jasypt:
  encryptor:
    password: M82tHF1EjfWpnXzG
    poolSize: 1
    algorithm: PBEWithMD5AndDES
    stringOutputType: base64
    keyObtentionIterations: 1000
    saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/center/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@iotdc3.register:8100/eureka/