apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: dc3
  name: dc3net
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              dc3.network/dc3net: "true"
  podSelector:
    matchLabels:
      dc3.version: develop
      dc3.network/dc3net: "true"