server:
  port: 8000

spring:
  application:
    name: @project.artifactId@
  security:
    user:
      name: ENC(bmSPDpfLV5VKUJhtcec+Hw==)
      password: ENC(egd+8ZV2DzqcWqv6IC7YxA==)
  redis:
    host: localhost
    port: 6379
    password:
  cloud:
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: Hystrix
            args:
              rate-limiter: fallbackcmd
              key-resolver: forward:/fallback
      routes:
        #注册中心 路由配置
        - id: register_web_route
          uri: lb://dc3-register
          predicates:
            - Path=/register/**
          filters:
            - StripPrefix=1
        - id: eureka_route
          uri: lb://dc3-register
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

jasypt:
  encryptor:
    password: M82tHF1EjfWpnXzG

logging:
  file: dc3/logs/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@iotdc3.register:8100/eureka/