server:
  port: 8000

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    enabled: true
    check-template: true
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  security:
    user:
      name: dc3
      password: dc3
  redis:
    host: dc3.redis
    port: 6379
    password: ${spring.security.user.password}
    database: 0
    timeout: 15S
    jedis:
      pool:
        max-idle: 16
        min-idle: 4
  transaction:
    rollback-on-commit-failure: true
  cache:
    type: redis
    cache-names: dc3-gateway-cache
    redis:
      time-to-live: 60S
  cloud:
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # auth
        - id: token_route
          uri: lb://dc3-auth/center/auth/token
          predicates:
            - Path=/api/v3/token
          filters:
            - StripPrefix=3
            - PrefixPath=/center/auth/token
            - AuthenticFilter
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: auth_route
          uri: lb://dc3-auth
          predicates:
            - Path=/api/v3/user/**
          filters:
            - AuthenticFilter
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        # rtmp
        - id: rtmp_route
          uri: lb://dc3-rtmp
          predicates:
            - Path=/api/v3/rtmp/**
          filters:
            - AuthenticFilter
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.cloud.gateway.route: ERROR
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR
  file:
    name: dc3/logs/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@dc3.register:8100/eureka/