server:
  port: 8000
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

logging:
  file: dc3/logs/dc3-gateway-product.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/

zuul:
  routes:
    register:
      path: /register/**
      serviceId: dc3-register
    eureka:
      path: /eureka/**
      serviceId: dc3-register
      stripPrefix: false