server:
  port: 8001
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: dc3/logs/dc3-gateway-dev.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/

# 网关配置
spring:
  cloud:
    gateway:
      routes:
        # 匹配指定路径的路由
        - id: path_route
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1
          # 匹配指定cookie的路由
        - id: cookie_route
          uri: http://www.taobao.com
          predicates:
            - Cookie=chocolate, value
          # 匹配指定请求头的路由
        - id: header_route
          uri: http://www.jd.com/
          predicates:
            - Header=X-Request-Id, \d+
          # 匹配指定请求参数的路由
        - id: param_route
          uri: http://tmall.com/
          predicates:
            - Query=param1,value
          # 匹配指定请求参数和请求头的路由
        - id: compose_route
          uri: http://www.oschina.net/
          predicates:
            - Query=param2
            - Header=Header-Route,value