server:
  port: 8000

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    enabled: true
    check-template: true
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  security:
    encode:
      key: t8KCtK0y63kA3kUx
    user:
      name: iotdc3
      password: iotdc3
  redis:
    host: iotdc3.redis
    port: 6379
    password: ${spring.security.user.password}
    database: 2
    timeout: 1H
  cloud:
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth_rest_api
          uri: lb://dc3-auth
          predicates:
            - Path=/api/v3/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: device_rest_api
          uri: lb://dc3-manager
          predicates:
            - Path=/api/v3/device/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: data_rest_api
          uri: lb://dc3-collect
          predicates:
            - Path=/api/v3/data/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: rtmp_rest_api
          uri: lb://dc3-rtmp
          predicates:
            - Path=/api/v3/rtmp/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: opc_rest_api
          uri: lb://dc3-opc
          predicates:
            - Path=/api/v3/opc/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: opcua_rest_api
          uri: lb://dc3-opc-ua
          predicates:
            - Path=/api/v3/opcua/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'
        - id: resource_rest_api
          uri: lb://dc3-resource
          predicates:
            - Path=/api/v3/resource/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/fallback'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: dc3/logs/${spring.application.name}.log
  level:
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@iotdc3.register:8100/eureka/