version: '3.3'

services:
  portainer:
    image:  portainer/portainer
    restart: always
    container_name: portainer
    hostname: dc3-portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dc3net:
        aliases:
          - dc3-portainer

  gateway:
    build:
      context: ../dc3-gateway/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-gateway:3.0
    restart: always
    ports:
      - 8000:8000
    container_name: dc3-gateway
    hostname: dc3-gateway
    networks:
      dc3net:
        aliases:
          - dc3-gateway

  register:
    build:
      context: ../dc3-center/dc3-register/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-register:3.0
    restart: always
    ports:
      - 8100:8100
    container_name: dc3-register
    hostname: dc3-register
    networks:
      dc3net:
        aliases:
          - dc3-register

  monitor:
    build:
      context: ../dc3-center/dc3-monitor/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-monitor:3.0
    restart: always
    ports:
      - 8200:8200
    container_name: dc3-monitor
    hostname: dc3-monitor
    networks:
      dc3net:
        aliases:
          - dc3-monitor

  auth:
    build:
      context: ../dc3-center/dc3-auth/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-auth:3.0
    restart: always
    ports:
      - 8300:8300
    container_name: dc3-auth
    hostname: dc3-auth
    networks:
      dc3net:
        aliases:
          - dc3-auth

  manager:
    build:
      context: ../dc3-center/dc3-manager/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-manager:3.0
    restart: always
    ports:
      - 8400:8400
    container_name: dc3-manager
    hostname: dc3-manager
    networks:
      dc3net:
        aliases:
          - dc3-manager

  data:
    build:
      context: ../dc3-center/dc3-data/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-data:3.0
    restart: always
    ports:
      - 8500:8500
    container_name: dc3-data
    hostname: dc3-data
    networks:
      dc3net:
        aliases:
          - dc3-data

  rtmp:
    build:
      context: ../dc3-transfer/dc3-rtmp/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-rtmp:3.0
    restart: always
    ports:
      - 8803:8803
    container_name: dc3-rtmp
    hostname: dc3-rtmp
    networks:
      dc3net:
        aliases:
          - dc3-rtmp

  virtual:
    build:
      context: ../dc3-driver/dc3-driver-virtual/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-driver-virtual:3.0
    restart: always
    ports:
      - 8600:8600
    container_name: dc3-driver-virtual
    hostname: dc3-driver-virtual
    networks:
      dc3net:
        aliases:
          - dc3-driver-virtual

  mysql:
    build:
      context: ./dependences/mysql/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-mysql:3.0
    restart: always
    ports:
      - 3306:3306
    container_name: dc3-mysql
    hostname: dc3-mysql
    networks:
      dc3net:
        aliases:
          - dc3-mysql

  mongo:
    build:
      context: ./dependences/mongo/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-mongo:3.0
    restart: always
    ports:
      - 27017:27017
    container_name: dc3-mongo
    hostname: dc3-mongo
    networks:
      dc3net:
        aliases:
          - dc3-mongo

  redis:
    build:
      context: ./dependences/redis/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-redis:3.0
    restart: always
    ports:
      - 6379:6379
    container_name: dc3-redis
    hostname: dc3-redis
    networks:
      dc3net:
        aliases:
          - dc3-redis

  rabbitmq:
    build:
      context: ./dependences/rabbitmq/
      dockerfile: ./Dockerfile
    image: pnoker/dc3-rabbitmq:3.0
    restart: always
    ports:
      - 5672:5672
      - 1883:1883
      - 61613:61613
      - 15672:15672
    container_name: dc3-rabbitmq
    hostname: dc3-rabbitmq
    networks:
      dc3net:
        aliases:
          - dc3-rabbitmq

  nginx:
    image: pnoker/alpine-nginx:rtmp
    restart: always
    ports:
      - 1935:1935
    container_name: dc3-nginx
    hostname: dc3-nginx
    networks:
      dc3net:
        aliases:
          - dc3-nginx

networks:
  dc3net:
    driver: 'bridge'
...
