server:
  port: 8814
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

feign:
  hystrix:
    enabled: true

netty:
  host: 127.0.0.1
  port: 7000

logging:
  file: dc3/logs/dc3-socket-product.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/