server:
  port: 8640
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

netty:
  host: 127.0.0.1
  port: 7000

logging:
  file: dc3/logs/dc3-socket-dev.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
