server:
  port: 8808
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: dc3-webapp

# 日志配置
logging:
  file: dc3/logs/dc3-webapp.log

#配置Actuator监控路径 * 表示全部监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/