server:
  port: 8808
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/dc3-webapp-product.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/