server:
  port: 8400
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
  security:
    user:
      name: iotdc3
      password: iotdc3

spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://iotdc3:iotdc3@localhost:8100/eureka/