server:
  port: 8800
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/dc3-register-dev.log

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/