server:
  port: 8810
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

logging:
  file: dc3/logs/dc3-register-product-1.log

eureka:
  instance:
    hostname: service
  client:
    serviceUrl:
      defaultZone: http://service:8801/eureka/