server:
  port: 8800
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

logging:
  file: dc3/logs/dc3-register-dev.log

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/