server:
  port: 8810
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/dc3-register-product-1.log

eureka:
  instance:
    hostname: service
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/