server:
  port: 8803
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  security:
    user:
      name: iotdc3
      password: iotdc3

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  level:
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR
    com.pnoker: DEBUG
  file:
    name: dc3/logs/transfer/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@iotdc3.register:8100/eureka/

rtmp:
  ffmpeg:
    window: D:/FFmpeg/bin/ffmpeg.exe
    unix: ffmpeg
  task:
    reconnect-interval: 5000
    reconnect-max-times: 10
  thread:
    core-pool-size: 4
    maximum-sool-size: 32
    keep-alive-time: 10