server:
  port: 8805
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  redis:
    host: localhost
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/iot-dc3?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  file: dc3/logs/dc3-service-dbs-product.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/,http://localhost:8801/eureka/