apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dc3-ingress
  namespace: dc3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /register
            backend:
              serviceName: dc3-register
              servicePort: 48081
          - path: /monitor
            backend:
              serviceName: dc3-monitor
              servicePort: 48082