driver:
  name: VirtualDriver
  description: @project.description@

server:
  port: 8600

spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    host: dc3-rabbitmq
    port: 5672
    username: dc3
    password: dc3

logging:
  level:
    com.pnoker: DEBUG
  file:
    name: dc3/logs/driver/${spring.application.name}.log