driver:
  name: VirtualDriver
  description: @project.description@
  connect:
    - displayName: 主机
      name: host
      type: string
      value: localhost
    - displayName: 端口
      name: port
      type: int
      value: 18600
  profile:
    - displayName: 位号
      name: tag
      type: string
      value: TAG

server:
  port: 8600

spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    host: dc3-rabbitmq
    port: 5672
    username: dc3
    password: dc3

logging:
  level:
    com.pnoker: DEBUG
  file:
    name: dc3/logs/driver/virtual/${spring.application.name}.log