driver:
  name: VirtualDriver
  description: @project.description@

server:
  port: 8600

spring:
  application:
    name: @project.artifactId@

logging:
  level:
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR
    com.pnoker: DEBUG
  file:
    name: dc3/logs/driver/${spring.application.name}.log