server:
  port: 8020
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/dc3-devices-dev.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
