remote:
  enable: true
  server:
    address: 127.0.0.1
    port: 8176
virtual:
  # unit second
  device:
    send-interval: 5
server:
  port: 8610
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  security:
    user:
      name: iotdc3
      password: iotdc3

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

logging:
  file: dc3/logs/virtual/${spring.application.name}.log
  level:
    org.springframework.data: WARN
    org.springframework.web: WARN
    org.mongodb.driver: WARN
    com.zaxxer.hikari: ERROR
    io.lettuce.core: WARN
    io.undertow: WARN
    com.netflix: WARN

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@iotdc3.register:8100/eureka/
