server:
  port: 8100
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: dc3-register
  security:
    user:
      name: iotdc3
      password: iotdc3
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: dc3/logs/center/dc3-register.log

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://iotdc3:iotdc3@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9