server:
  port: 8805
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: dc3-dbs
  redis:
    host: localhost
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/dc_3?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    sql-script-encoding: utf-8

# 日志配置
logging:
  file: dc3-logs/dc3-dbs.log

#配置Actuator监控路径 * 表示全部监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/