server:
  port: 8200
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2

spring:
  application:
    name: @project.artifactId@
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: dc3
      password: dc3
  boot:
    admin:
      ui:
        title: DC3 Monitoring Center
        favicon: images/icon/favicon.ico
        favicon-danger: images/icon/favicon-danger.ico
        brand: <img src="images/logo/dc3-logo.png"><span>DC3 Monitoring Center</span>

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    org.springframework.data: ERROR
    org.springframework.web: ERROR
    org.mybatis.spring: ERROR
    org.mongodb.driver: ERROR
    com.zaxxer.hikari: ERROR
    com.ulisesbocchio: ERROR
    io.lettuce.core: ERROR
    io.undertow: ERROR
    com.netflix: ERROR
  file:
    name: dc3/logs/center/${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@dc3.register:8100/eureka/