apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dc3-opcua
  namespace: dc3
  name: dc3-opcua
spec:
  ports:
  - name: "8802"
    port: 8802
    targetPort: 8802
  selector:
    io.kompose.service: dc3-opcua
status:
  loadBalancer: {}
