apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dc3-mongo
  namespace: dc3
  name: dc3-mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: dc3-mongo
status:
  loadBalancer: {}
