apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dc3-rtmp
  name: dc3-rtmp
spec:
  ports:
  - name: "8803"
    port: 8803
    targetPort: 8803
  selector:
    io.kompose.service: dc3-rtmp
status:
  loadBalancer: {}
