apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dc3-nginx
  namespace: dc3
  name: dc3-nginx
spec:
  ports:
  - name: "1935"
    port: 1935
    targetPort: 1935
  selector:
    io.kompose.service: dc3-nginx
status:
  loadBalancer: {}
