apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-mysql
  namespace: dc3
  name: dc3-mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-mysql