apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-manager
  namespace: dc3
  name: dc3-manager
spec:
  ports:
    - name: "8600"
      port: 8600
      targetPort: 8600
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-manager