apiVersion: v1
kind: Service
metadata:
  labels:
    dc3.service: dc3-monitor
  namespace: dc3
  name: dc3-monitor
spec:
  ports:
    - name: "8200"
      port: 8200
      targetPort: 8200
  selector:
    dc3.version: develop
    dc3.network/dc3net: "true"
    dc3.service: dc3-monitor